CATEGORIES = [
    ('mesin & komponen', 'Mesin & Komponen'),
    ('kelistrikan', 'Kelistrikan'),
    ('bahan bakar', 'Bahan Bakar'),
    ('pendingin', 'Pendingin'),
    ('pelumasan', 'Pelumasan'),
    ('rem', 'Rem'),
    ('kopling & transmisi', 'Kopling & Transmisi'),
    ('kaki-kaki & suspensi', 'Kaki-kaki & Suspensi'),
    ('ban & velg', 'Ban & Velg'),
    ('kemudi', 'Kemudi'),
    ('body', 'Body'),
    ('aksesoris', 'Aksesoris'),
    ('interior', 'Interior'),
    ('knalpot', 'Knalpot'),
    ('rantai & gir', 'Rantai & Gir'),
]