TIPE = [
    ('f1-zr-jpt-z', 'F1 ZR/Jpt Z'),
    ('rx-king', 'RX King'),
    ('grand', 'Grand'),
    ('supra', 'Supra'),
    ('beat', 'Beat'),
    ('revo-abs', 'Revo Abs'),
    ('vixion-new', 'Vixion NEW'),
    ('vario', 'Vario'),
    ('beat-fi', 'Beat FI'),
    ('mio-m3', 'Mio M3'),
    ('mio-j', 'Mio J'),
    ('genio', 'GENIO'),
    ('vixion', 'Vixion'),
    ('jupiter-mx', 'Jupiter MX'),
    ('megapro', 'Megapro'),
    ('tiger', 'Tiger'),
    ('smash', 'Smash'),
    ('shogun125-sp', 'Shogun125 SP'),
    ('supra-x-125', 'Supra X 125'),
    ('jupz\'06-vegar', 'JupZ\'06/VegaR'),
    ('jupiter-z', 'Jupiter Z'),
    ('supra-fit-new', 'Supra Fit New'),
    ('karisma', 'Karisma'),
    ('shogun-125-fl', 'Shogun 125 FL'),
    ('mio-soul', 'Mio Soul'),
    ('mio', 'Mio'),
    ('nmax', 'Nmax'),
    ('spin125', 'Spin125'),
    ('vario-150-esp', 'Vario 150 ESP'),
    ('supra-x', 'SUPRA X'),
    ('force-1', 'Force - 1'),
    ('klx', 'KLX'),
    ('fi-zr', 'FI-ZR'),
    ('vario-beat', 'Vario/Beat'),
    ('beatpop-scoopy', 'BeatPop/Scoopy'),
    ('beat-genio', 'Beat Genio'),
    ('scoopy-fi-esp', 'Scoopy FI ESP'),
    ('beat-esp', 'Beat ESP'),
    ('megapronew', 'MegaProNew'),
    ('suprax125', 'SupraX125'),
    ('blade-new', 'Blade New'),
    ('ninja-150', 'Ninja 150'),
    ('cbr150', 'CBR150'),
    ('vario-125', 'Vario 125'),
    ('ninja', 'Ninja'),
    ('all', 'ALL'),
    ('satria-fu', 'Satria FU'),
    ('tiger-pro-nt', 'Tiger/Pro NT'),
    ('vega-zr', 'Vega ZR'),
    ('vario-150', 'Vario 150'),
    ('rxk-crypton', 'RXK/Crypton'),
    ('cb150r', 'CB150R'),
    ('cb150', 'CB150'),
    ('crf150', 'CRF150'),
    ('scorpio-z', 'Scorpio Z'),
    ('beat-pop', 'Beat Pop'),
    ('glpro', 'GLPro'),
    ('megapro-mono', 'Megapro Mono'),
    ('rxking-new', 'RXKING NEW'),
    ('vario-cbs', 'Vario/CBS'),
    ('pro-nt', 'Pro NT'),
    ('gl100', 'GL100'),
    ('revo-blade', 'Revo/Blade'),
    ('shogun', 'SHOGUN'),
    ('gl-pro-nt', 'GL PRO NT'),
    ('vario-techno', 'Vario Techno'),
    ('rxk-cobra', 'RXK Cobra'),
    ('satria', 'Satria'),
    ('crypton', 'Crypton'),
    ('jupiter-z\'03', 'Jupiter Z\'03'),
    ('mio-new', 'Mio NEW'),
    ('mio-new\'08', 'Mio New\'08'),
    ('-', '-'),
    ('megapro/pront', 'Megapro/PRONT'),
    ('supra-fit', 'Supra/FIT'),
    ('jupiter-z-mx', 'Jupiter Z/MX'),
    ('megapro-10', 'Megapro 10'),
    ('blade', 'Blade'),
    ('klx150', 'KLX150'),
    ('satria-fu150', 'Satria FU150'),
    ('scorpio', 'Scorpio'),
    ('aerox-155', 'Aerox 155'),
    ('supra-grand', 'Supra/Grand'),
    ('vario150-newled', 'Vario150 NEWLED'),
    ('vario-cbs-f1', 'Vario CBS F1'),
    ('megapronew-(rear)', 'MegaProNew (REAR)'),
    ('satria-f150(rear)', 'Satria F150(REAR)'),
    ('beatnew-vario-cbs', 'BeatNew/Vario CBS'),
    ('satria-fu-new', 'Satria FU New'),
    ('r15-vixion 2018', 'R15/ Vixion 2018'),
    ('pcx', 'PCX'),
    ('pcx-new', 'PCX NEW'),
    ('crf-vario', 'CRF/VARIO'),
    ('cbr150-led', 'CBR150 LED'),
    ('revo-fit', 'Revo Fit'),
    ('fino-fi', 'Fino FI'),
    ('spacy', 'Spacy'),
    ('beat-new fi', 'Beat New FI'),
    ('aerox', 'Aerox'),
    ('nmax-new', 'Nmax New'),
    ('fazzio', 'FAZZIO'),
    ('blade-new fi', 'Blade New FI'),
    ('verza', 'Verza'),
    ('neotech', 'Neotech'),
    ('vixion-2007', 'Vixion 2007'),
    ('revo-fi', 'Revo FI'),
    ('sonic', 'Sonic'),
    ('c800-a', 'C800 A'),
    ('supra125/kph', 'Supra125/KPH'),
    ('jupiter', 'Jupiter'),
    ('prima/grand', 'Prima/Grand'),
    ('vega-zr-new', 'VEGA ZR NEW'),
    ('satria-fu-series3', 'Satria FU series3'),
    ('jupiter-mx-new11', 'Jupiter MX NEW11'),
    ('smash-new', 'Smash NEW'),
    ('revo-abs-fi', 'Revo Abs FI'),
    ('megapro\'10/verza', 'Megapro\'10/Verza'),
    ('cb150new/sonic', 'CB150New/Sonic'),
    ('jup-mx-mio', 'Jup MX/Mio'),
    ('supra125-helm-in', 'Supra125 Helm in'),
    ('supra125-new', 'Supra125 New'),
    ('pcx160', 'PCX160'),
    ('prima', 'Prima'),
    ('jupiter-mx-new', 'Jupiter MX New'),
    ('crf', 'CRF'),
    ('revo', 'Revo'),
    ('rxs', 'RXS'),
    ('beat-fi-esp/pop', 'Beat FI/ESP/POP'),
    ('vario150-new', 'Vario150 New'),
    ('vario125-esp', 'Vario125 ESP'),
    ('scoopy', 'Scoopy'),
    ('r15', 'R15'),
    ('win', 'Win'),
    ('vario-160', 'Vario 160'),
    ('pcx150-new', 'PCX150 New'),
    ('vario125esp', 'Vario125ESP'),
    ('satria-6s', 'SATRIA 6S'),
    ('cb150-led', 'CB150 LED'),
    ('vario-150 new', 'Vario 150 New'),
    ('smash-110', 'Smash 110'),
    ('mio125m3', 'Mio125M3'),
    ('vario125-cbs', 'Vario125 CBS'),
    ('xeon', 'Xeon'),
    ('byson', 'Byson'),
    ('mio-j-vixion new', 'Mio J/Vixion New'),
    ('shogun-125', 'Shogun 125'),
    ('vixion-jupitermx', 'Vixion/JupiterMX'),
    ('vegazr-jupiterz', 'VegaZR/JupiterZ'),
    ('cs-1', 'CS-1'),
    ('max-neotech', 'MAX NEOTECH'),
    ('spin', 'Spin'),
    ('blade-fi', 'Blade FI'),
    ('cb150-old', 'CB150 OLD'),
    ('beat-esp-genio', 'Beat Esp/Genio'),
    ('scoopy-fi', 'Scoopy FI'),
    ('jupiter-z-new', 'Jupiter Z New'),
    ('supra125-fi-14', 'Supra125 FI 14'),
    ('mio-m3-nmax', 'Mio M3 / NMAX'),
    ('vario125 fi', 'Vario125 FI'),
    ('jupiter-vegar', 'Jupiter/VegaR'),
    ('jupiter-mx(rear)', 'Jupiter MX(rear)'),
    ('cbled-beatled-genio-pcx160', 'Cbled/Beatled/Genio/Pcx160'),
    ('legenda', 'LEGENDA'),
    ('beat-fi-esp', 'Beat FI ESP'),
    ('pcx125', 'PCX125'),
    ('vixion-2010', 'Vixion 2010'),
    ('pcx-150', 'PCX 150'),
    ('supra-125-fi', 'Supra 125 FI'),
    ('jupiter-z1', 'Jupiter Z1'),
    ('supra125-fi', 'Supra125 FI'),
    ('aerox-lexi-nmax', 'Aerox/Lexi/Nmax'),
    ('gl125', 'GL125'),
    ('cb150r-new', 'CB150R NEW'),
    ('beat-street', 'Beat Street'),
    ('cb100k2', 'CB100K2'),
    ('j.mx-vixion', 'J.MX / Vixion'),
    ('mio-nouvo', 'MIO / NOUVO'),
    ('freego', 'Freego'),
    ('supra-fit', 'Supra Fit'),
    ('jupiter-z\'11', 'Jupiter Z\'11'),
    ('mio\'09-soul', 'Mio\'09/soul'),
    ('mio\'11', 'Mio\'11'),
    ('mio-sporty', 'Mio Sporty'),
    ('aerox-nmax', 'Aerox/Nmax'),
    ('smash-shogun', 'Smash/shogun'),
    ('aerox-nmax-new', 'Aerox/Nmax New'),
    ('d\'tracker', 'D\'Tracker'),
    ('beat-led', 'Beat LED'),
    ('vario-110-fi', 'Vario 110 FI'),
    ('vario125-led-2018', 'Vario125 LED 2018'),
    ('beat-fi-street', 'Beat FI/Street'),
    ('v.160-pcx160-150-adv', 'V.160/PCX160/150/ADV'),
    ('nmax-aerox', 'Nmax/Aerox'),
    ('megapro-adv', 'Megapro ADV'),
    ('vixion-13', 'VIXION 13'),
    ('megapro-primus', 'Megapro Primus'),
    ('nmax-mio-m3', 'Nmax/Mio M3'),
    ('gtr-sonic-cb2016-21', 'GTR/SONIC/CB2016-21'),
    ('beat-vario', 'Beat/Vario'),
    ('nmax.n-aerox.n', 'NMAX.N/AEROX.N'),
    ('vario-techno125-fi', 'Vario Techno125/FI'),
    ('vegazr-mx-11', 'VegaZr/Mx 11'),
    ('mio-j', 'Mio/J'),
    ('revo-vario125', 'Revo/vario125'),
    ('smash-fitnew', 'Smash/Fitnew'),
    ('spin125new', 'Spin125NEW'),
    ('vegarnew', 'VegaRNew'),
]