# Generated by Django 5.0.7 on 2025-06-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_barang_kategori_barang_tipe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='gambar',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
