# Generated by Django 5.0.7 on 2025-06-14 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_transaksimasuk_barang_alter_barang_merk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransaksiKeluar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('no_bukti', models.CharField(max_length=10, unique=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('tanggal_pembuatan', models.DateTimeField(auto_now_add=True)),
                ('terakhir_edit', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransaksiMasuk',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('no_bukti', models.CharField(max_length=10, unique=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('tanggal_pembuatan', models.DateTimeField(auto_now_add=True)),
                ('terakhir_edit', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransaksiKeluarBarang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.barang')),
                ('transaksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.transaksikeluar')),
            ],
        ),
        migrations.AddField(
            model_name='transaksikeluar',
            name='barang',
            field=models.ManyToManyField(through='myapp.TransaksiKeluarBarang', to='myapp.barang'),
        ),
        migrations.CreateModel(
            name='TransaksiMasukBarang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.barang')),
                ('transaksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.transaksimasuk')),
            ],
        ),
        migrations.AddField(
            model_name='transaksimasuk',
            name='barang',
            field=models.ManyToManyField(through='myapp.TransaksiMasukBarang', to='myapp.barang'),
        ),
    ]
