# Generated by Django 5.0.7 on 2025-06-14 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_transaksikeluar_transaksimasuk_transaksikeluarbarang_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaksikeluarbarang',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='transaksimasukbarang',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='transaksikeluarbarang',
            table='myapp_transaksikeluarbarang',
        ),
        migrations.AlterModelTable(
            name='transaksimasukbarang',
            table='myapp_transaksimasukbarang',
        ),
    ]
