# Generated by Django 5.0.7 on 2025-06-14 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_transaksikeluarbarang_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaksikeluarbarang',
            options={},
        ),
        migrations.AlterModelOptions(
            name='transaksimasukbarang',
            options={},
        ),
        migrations.AlterModelTable(
            name='transaksikeluarbarang',
            table=None,
        ),
        migrations.AlterModelTable(
            name='transaksimasukbarang',
            table=None,
        ),
    ]
