# Generated by Django 5.0.7 on 2025-06-19 19:07

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_transaksikeluarbarang_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailinvoice',
            old_name='tanggal',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='detailpesanan',
            old_name='tanggal_pesanan',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='created_at',
            new_name='tanggal',
        ),
        migrations.RenameField(
            model_name='pesanan',
            old_name='created_at',
            new_name='tanggal_pesanan',
        ),
        migrations.RemoveField(
            model_name='detailinvoice',
            name='jatuh_tempo',
        ),
        migrations.RemoveField(
            model_name='detailinvoice',
            name='top',
        ),
        migrations.RemoveField(
            model_name='detailpesanan',
            name='alamat_kirim',
        ),
        migrations.RemoveField(
            model_name='detailpesanan',
            name='jatuh_tempo',
        ),
        migrations.RemoveField(
            model_name='detailpesanan',
            name='keterangan',
        ),
        migrations.RemoveField(
            model_name='detailpesanan',
            name='kurir',
        ),
        migrations.RemoveField(
            model_name='detailpesanan',
            name='top',
        ),
        migrations.RemoveField(
            model_name='faktur',
            name='piutang',
        ),
        migrations.RemoveField(
            model_name='hutang',
            name='nilai_bayar',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='hutang',
        ),
        migrations.RemoveField(
            model_name='piutang',
            name='nilai_bayar',
        ),
        migrations.RemoveField(
            model_name='returbeli',
            name='barang',
        ),
        migrations.RemoveField(
            model_name='returjual',
            name='barang',
        ),
        migrations.AddField(
            model_name='invoice',
            name='jatuh_tempo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='top',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pesanan',
            name='alamat_kirim',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pesanan',
            name='jatuh_tempo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pesanan',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pesanan',
            name='kurir',
            field=models.CharField(choices=[('jne', 'JNE'), ('tiki', 'TIKI'), ('j&t', 'J&T'), ('pos indonesia', 'Pos Indonesia')], default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='pesanan',
            name='top',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='barang',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='barang',
            name='harga_modal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='customer',
            name='alamat_lengkap',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='detailinvoice',
            name='qty_retur',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detailpesanan',
            name='qty_retur',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hutang',
            name='total_pelunasan',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='hutang',
            name='total_potongan',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='bruto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='diskon_invoice',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='netto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='no_referensi',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='potongan',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='sisa_bayar',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='katalog',
            name='is_katalog_utama',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pesanan',
            name='bruto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='pesanan',
            name='diskon_pesanan',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='pesanan',
            name='netto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='pesanan',
            name='no_referensi',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='piutang',
            name='total_pelunasan',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='piutang',
            name='total_potongan',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19),
        ),
        migrations.CreateModel(
            name='HutangInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai_bayar', models.DecimalField(decimal_places=2, max_digits=19)),
                ('hutang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.hutang')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.invoice')),
            ],
        ),
        migrations.AddField(
            model_name='hutang',
            name='invoice',
            field=models.ManyToManyField(through='myapp.HutangInvoice', to='myapp.invoice'),
        ),
        migrations.CreateModel(
            name='PiutangFaktur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai_bayar', models.DecimalField(decimal_places=2, max_digits=19)),
                ('faktur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.faktur')),
                ('piutang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.piutang')),
            ],
        ),
        migrations.AddField(
            model_name='piutang',
            name='faktur',
            field=models.ManyToManyField(through='myapp.PiutangFaktur', to='myapp.faktur'),
        ),
        migrations.CreateModel(
            name='ReturBeliBarang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.barang')),
                ('retur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.returbeli')),
            ],
        ),
        migrations.CreateModel(
            name='ReturJualBarang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.barang')),
                ('retur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.returjual')),
            ],
        ),
    ]
