# Generated by Django 5.0.7 on 2025-06-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_tanggal_detailinvoice_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returbeli',
            name='barang',
            field=models.ManyToManyField(through='myapp.ReturBeliBarang', to='myapp.barang'),
        ),
        migrations.AddField(
            model_name='returjual',
            name='barang',
            field=models.ManyToManyField(through='myapp.ReturJualBarang', to='myapp.barang'),
        ),
    ]
