# Generated by Django 5.0.7 on 2025-06-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_katalog_barang_katalogbarang'),
    ]

    operations = [
        migrations.AddField(
            model_name='katalog',
            name='barang',
            field=models.ManyToManyField(through='myapp.KatalogBarang', to='myapp.barang'),
        ),
    ]
