# Generated by Django 5.0.7 on 2025-06-24 16:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_katalog_barang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesanan',
            name='kurir',
            field=models.CharField(choices=[('staff', 'Staff'), ('penangkutan', 'Pengangkutan')], default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='pesanan',
            name='ongkir',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='pesanan',
            name='ppn',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='pesanan',
            name='top',
            field=models.IntegerField(default=0),
        ),
    ]
