# Generated by Django 5.0.7 on 2025-06-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_pesanan_kurir_alter_pesanan_ongkir_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesanan',
            name='alamat_kirim',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
