# Generated by Django 5.0.7 on 2025-06-24 16:53

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_pesanan_alamat_kirim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailpesanan',
            name='barang_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.barang'),
        ),
        migrations.AlterField(
            model_name='detailpesanan',
            name='diskon_barang',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='detailpesanan',
            name='qty_retur',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
