# Generated by Django 5.0.7 on 2025-06-26 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_detailpesanan_barang_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='katalogbarang',
            name='katalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promosi_barang', to='myapp.katalog'),
        ),
    ]
