# Generated by Django 5.0.7 on 2025-06-27 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_userlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLog',
        ),
    ]
