# Generated by Django 5.0.7 on 2025-06-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_delete_userlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faktur',
            name='potongan',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=19, null=True),
        ),
    ]
