# Generated by Django 5.0.7 on 2025-06-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_faktur_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('lunas', 'Lunas'), ('belum_lunas', 'Belum Lunas'), ('jatuh_tempo', 'Jatuh Tempo')], default='belum_lunas', max_length=30),
        ),
    ]
