# Generated by Django 5.0.7 on 2025-06-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_invoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='tanggal',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
