# Generated by Django 5.0.7 on 2025-07-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_invoice_tanggal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persenbonus',
            name='barang_id',
        ),
        migrations.AlterField(
            model_name='hutang',
            name='invoice',
            field=models.ManyToManyField(related_name='hutang_set', through='myapp.HutangInvoice', to='myapp.invoice'),
        ),
    ]
