# Generated by Django 5.0.7 on 2025-07-01 11:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_remove_persenbonus_barang_id_alter_hutang_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='returbelibarang',
            name='diskon_barang',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=19),
        ),
        migrations.AddField(
            model_name='returjualbarang',
            name='diskon_barang',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=19),
        ),
    ]
