# Generated by Django 5.0.7 on 2025-07-01 18:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_returbelibarang_diskon_barang_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailinvoice',
            name='diskon_barang',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='ppn',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pesanan',
            name='bruto',
            field=models.DecimalField(decimal_places=0, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='pesanan',
            name='diskon_pesanan',
            field=models.DecimalField(decimal_places=0, default=Decimal('0.00'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='pesanan',
            name='netto',
            field=models.DecimalField(decimal_places=0, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='pesanan',
            name='ongkir',
            field=models.DecimalField(decimal_places=0, default=Decimal('0.00'), max_digits=19),
        ),
    ]
