# Generated by Django 5.0.7 on 2025-07-02 12:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_alter_detailinvoice_diskon_barang_alter_invoice_ppn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returbeli',
            name='ongkir',
            field=models.DecimalField(decimal_places=0, default=Decimal('0.00'), max_digits=19),
        ),
        migrations.AddField(
            model_name='returjual',
            name='ongkir',
            field=models.DecimalField(decimal_places=0, default=Decimal('0.00'), max_digits=19),
        ),
        migrations.AlterField(
            model_name='returbelibarang',
            name='diskon_barang',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='returjualbarang',
            name='diskon_barang',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=5),
        ),
    ]
