# Generated by Django 5.0.7 on 2025-07-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_returbeli_ongkir_returjual_ongkir_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faktur',
            name='potongan',
        ),
        migrations.AddField(
            model_name='piutangfaktur',
            name='potongan',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=19, null=True),
        ),
    ]
