# Generated by Django 5.0.7 on 2025-07-10 14:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_remove_faktur_potongan_piutangfaktur_potongan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='potongan',
        ),
        migrations.AddField(
            model_name='hutanginvoice',
            name='potongan',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=19),
        ),
    ]
