from django.urls import path, re_path
from . import views

urlpatterns = [
    path('', views.katalog, name='katalog'),
    path('rem/', views.katalogbrg, name='katalogbrg'),
    path('rem/deskripsi/', views.deskripsi, name='deskripsi'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('login/', views.login, name='login'),
    path('pesanan/<int:pesanan_id>/update-status/', views.update_status_pesanan, name='update_status_pesanan'),
    path('pesanan/<int:pesanan_id>/delete/', views.delete_pesanan, name='delete_pesanan'),
    path('pesanan/<str:status>/', views.pesanan, name='pesanan'),
    path('pesanan/tambah/', views.tambah_pesanan, name='tambah_pesanan'),
    path('barang/', views.barang, name='barang'),
    path('barang/rendah/', views.barang_rendah, name='barang_rendah'),
    path('barang/laku/', views.barang_laku, name='barang_laku'),
    path('barang/tambah/', views.tambah_barang, name='tambah_barang'),
    path('katalog/', views.admin_katalog, name='admin_katalog'),
    path('katalog/tambah/', views.tambah_brgkatalog, name='tambah_brgkatalog'),
    path('barang/masuk/', views.transaksi_masuk, name='transaksi_masuk'),
    path('barang/keluar/', views.transaksi_keluar, name='transaksi_keluar'),
    path('barang/masuk/tambah/', views.tambah_masuk, name='tambah_masuk'),
    path('barang/keluar/tambah/', views.tambah_keluar, name='tambah_keluar'),
    path('supplier/', views.supplier, name='supplier'),
    path('supplier/tambah/', views.tambah_supplier, name='tambah_supplier'),
    path('customer/', views.customer, name='customer'),
    path('customer/tambah/', views.tambah_customer, name='tambah_customer'),
    path('pembelian/invoice/', views.invoice, name='invoice'),
    path('pembelian/invoice/belumlunas/', views.invoice_belum, name='invoice_belum'),
    path('pembelian/invoice/jatuhtempo/', views.invoice_jatuh, name='invoice_jatuh'),
    path('pembelian/invoice/tambah/', views.tambah_invoice, name='tambah_invoice'),
    path('pembelian/retur/', views.retur_beli, name='retur_beli'),
    path('pembelian/retur/tambah/', views.tambah_returbeli, name='tambah_returbeli'),
    path('pembelian/pembayaran/hutang/', views.hutang, name='pembayaran_hutang'),
    path('pembelian/pembayaran/hutang/tambah/', views.tambah_bayarhutang, name='tambah_bayarhutang'),
    path('penjualan/faktur/', views.faktur, name='faktur'),
    path('penjualan/faktur/belumlunas/', views.faktur_belum, name='faktur_belum'),
    path('penjualan/faktur/jatuhtempo/', views.faktur_jatuh, name='faktur_jatuh'),
    path('penjualan/retur/', views.retur_jual, name='retur_jual'),
    path('penjualan/retur/tambah/', views.tambah_returjual, name='tambah_returjual'),
    path('penjualan/pembayaran/piutang/', views.piutang, name='pembayaran_piutang'),
    path('penjualan/pembayaran/piutang/tambah/', views.tambah_bayarpiutang, name='tambah_bayarpiutang'),
    path('api/simpan-barang/', views.simpan_barang, name='simpan_barang'),
    path('api/hapus-barang/<int:barang_id>/', views.hapus_barang, name='hapus_barang'),
    path('bantuan/', views.bantuan, name='bantuan'),
    path('not-allowed/', views.halaman403, name='403'),
    re_path(r'^.*$', views.halaman404, name='404'),
]
